# Generated by Django 6.0.2 on 2026-03-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên căn hộ")),
                (
                    "price",
                    models.CharField(max_length=50, verbose_name="Giá tiền (VNĐ)"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Địa chỉ")),
                ("desc", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="apartments/",
                        verbose_name="Hình ảnh",
                    ),
                ),
                ("lat", models.FloatField(verbose_name="Vĩ độ (Latitude)")),
                ("lng", models.FloatField(verbose_name="Kinh độ (Longitude)")),
            ],
            options={
                "verbose_name": "Căn hộ",
                "verbose_name_plural": "Danh sách Căn hộ",
            },
        ),
    ]
