# Generated by Django 5.2.10 on 2026-03-27 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên căn hộ')),
                ('price', models.CharField(max_length=50, verbose_name='Giá tiền (VNĐ)')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('desc', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='apartments/', verbose_name='Hình ảnh')),
                ('lat', models.FloatField(verbose_name='Vĩ độ (Latitude)')),
                ('lng', models.FloatField(verbose_name='Kinh độ (Longitude)')),
            ],
            options={
                'verbose_name': 'Căn hộ',
                'verbose_name_plural': 'Danh sách Căn hộ',
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Tiêu đề ảnh')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ngắn')),
                ('image', models.ImageField(upload_to='apartments/gallery/', verbose_name='Ảnh thư viện')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='myapp.apartment', verbose_name='Căn hộ')),
            ],
            options={
                'verbose_name': 'Ảnh căn hộ',
                'verbose_name_plural': 'Thư viện ảnh căn hộ',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, verbose_name='Tên / số phòng')),
                ('max_people', models.PositiveIntegerField(default=1, verbose_name='Số người tối đa')),
                ('is_available', models.BooleanField(default=True, verbose_name='Phòng còn trống')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='myapp.apartment', verbose_name='Căn hộ')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Danh sách Phòng',
                'ordering': ['apartment__name', 'room_name'],
                'unique_together': {('apartment', 'room_name')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('check_in', models.DateField(verbose_name='Ngày nhận phòng')),
                ('check_out', models.DateField(verbose_name='Ngày trả phòng')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Số khách')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('checked_in', 'Đang ở'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myapp.apartment', verbose_name='Căn hộ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='myapp.room', verbose_name='Phòng')),
            ],
            options={
                'verbose_name': 'Đơn đặt phòng',
                'verbose_name_plural': 'Danh sách Đơn đặt phòng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên dịch vụ')),
                ('icon', models.CharField(blank=True, default='fa-check-circle', max_length=50, verbose_name='Icon Font Awesome')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả dịch vụ')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='myapp.apartment', verbose_name='Căn hộ')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ căn hộ',
                'ordering': ['name'],
                'unique_together': {('apartment', 'name')},
            },
        ),
    ]
