# Generated by Django 6.0.1 on 2026-03-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_apartment_momo_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Chuyển khoản"),
                    ("momo", "MoMo"),
                    ("cash", "Tiền mặt"),
                ],
                default="bank_transfer",
                max_length=50,
                verbose_name="Phương thức thanh toán",
            ),
        ),
    ]
