# Generated by Django 6.0.1 on 2026-03-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_sync_booking_payment_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="room",
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Đơn thuê căn hộ",
                "verbose_name_plural": "Danh sách Đơn thuê căn hộ",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateField(verbose_name="Ngày nhận nhà"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateField(verbose_name="Ngày trả nhà"),
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
