# Generated by Django 6.0.1 on 2026-04-07 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_booking_nightly_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 sao"),
                            (2, "2 sao"),
                            (3, "3 sao"),
                            (4, "4 sao"),
                            (5, "5 sao"),
                        ],
                        verbose_name="Số sao",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Bình luận")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="myapp.apartment",
                        verbose_name="Căn hộ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartment_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tài khoản",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá căn hộ",
                "verbose_name_plural": "Đánh giá căn hộ",
                "ordering": ["-updated_at", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("apartment", "user"),
                        name="unique_apartment_review_per_user",
                    )
                ],
            },
        ),
    ]
