# Generated by Django 6.0.1 on 2026-04-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_apartmentreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntroductionPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_badge", models.CharField(default="CanHo24h", max_length=80)),
                (
                    "hero_title",
                    models.CharField(
                        default="Không gian thuê căn hộ nghỉ dưỡng chỉn chu và đáng tin cậy",
                        max_length=220,
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="Giới thiệu rõ hơn về dịch vụ, trải nghiệm lưu trú và lý do khách hàng chọn CanHo24h cho những kỳ nghỉ ngắn ngày hoặc chuyến công tác dài ngày."
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="intro/"),
                ),
                (
                    "story_title",
                    models.CharField(
                        default="Điều gì khiến CanHo24h khác biệt?", max_length=180
                    ),
                ),
                (
                    "story_content",
                    models.TextField(
                        blank=True,
                        default="<p>CanHo24h tập trung vào trải nghiệm thuê nguyên căn rõ ràng, minh bạch và dễ thao tác. Từ lúc xem căn hộ, kiểm tra lịch trống, đặt cọc đến khi nhận căn, mọi bước đều được tối ưu để khách hàng yên tâm hơn.</p>",
                    ),
                ),
                (
                    "feature_one_title",
                    models.CharField(default="Căn hộ chọn lọc", max_length=120),
                ),
                (
                    "feature_one_description",
                    models.TextField(
                        default="Ưu tiên những căn hộ có hình ảnh rõ, thông tin minh bạch và tiện ích phù hợp cho khách nghỉ dưỡng hoặc công tác."
                    ),
                ),
                (
                    "feature_two_title",
                    models.CharField(default="Đặt cọc dễ hiểu", max_length=120),
                ),
                (
                    "feature_two_description",
                    models.TextField(
                        default="Khách hàng chỉ thanh toán phần cọc trước, phần còn lại xử lý khi nhận căn để dễ theo dõi và chủ động hơn."
                    ),
                ),
                (
                    "feature_three_title",
                    models.CharField(default="Theo dõi bằng GIS", max_length=120),
                ),
                (
                    "feature_three_description",
                    models.TextField(
                        default="Tìm căn hộ theo bản đồ, khu vực, khoảng cách và thời gian di chuyển giúp quyết định thuê nhanh hơn."
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="Sẵn sàng tìm căn hộ phù hợp cho chuyến đi của bạn?",
                        max_length=180,
                    ),
                ),
                (
                    "cta_description",
                    models.TextField(
                        default="Khám phá danh sách căn hộ nghỉ dưỡng nổi bật, kiểm tra lịch trống và gửi yêu cầu thuê chỉ trong vài bước."
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(default="Khám phá căn hộ", max_length=80),
                ),
                ("cta_button_link", models.CharField(default="/map/", max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trang giới thiệu",
                "verbose_name_plural": "Trang giới thiệu",
            },
        ),
    ]
