# Generated by Django 6.0.1 on 2026-04-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_introductionpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="introductionpage",
            name="cta_image",
            field=models.ImageField(blank=True, null=True, upload_to="intro/"),
        ),
        migrations.AddField(
            model_name="introductionpage",
            name="hero_image_secondary",
            field=models.ImageField(blank=True, null=True, upload_to="intro/"),
        ),
        migrations.AddField(
            model_name="introductionpage",
            name="story_image",
            field=models.ImageField(blank=True, null=True, upload_to="intro/"),
        ),
    ]
