# Generated by Django 6.0.1 on 2026-04-14 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_introductionpage_cta_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("code", models.CharField(max_length=6, verbose_name="Mã xác nhận")),
                ("expires_at", models.DateTimeField(verbose_name="Hết hạn lúc")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Đã dùng lúc"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tài khoản",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mã quên mật khẩu",
                "verbose_name_plural": "Mã quên mật khẩu",
                "ordering": ["-created_at"],
            },
        ),
    ]
