# Generated by Django 5.2.10 on 2026-04-14 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_introductionpage_cta_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email nhan OTP')),
                ('purpose', models.CharField(choices=[('forgot_password', 'Quen mat khau'), ('change_password', 'Doi mat khau')], max_length=30, verbose_name='Muc dich')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Ma OTP da bam')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='So lan thu')),
                ('expires_at', models.DateTimeField(verbose_name='Het han luc')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Da su dung luc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_otps', to=settings.AUTH_USER_MODEL, verbose_name='Tai khoan')),
            ],
            options={
                'verbose_name': 'Ma OTP mat khau',
                'verbose_name_plural': 'Ma OTP mat khau',
                'ordering': ['-created_at'],
            },
        ),
    ]
